// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NsPluginExample.DAL.Contexts;

namespace NsPluginExample.DAL.Migrations
{
    [DbContext(typeof(NsPluginExampleContext))]
    partial class NsPluginExampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NsPluginExample.Domain.Models.NsModels.OAuth.OAuth2Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessToken");

                    b.Property<int>("ExpiresIn");

                    b.Property<string>("RefreshToken");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("OAuthToken");
                });
#pragma warning restore 612, 618
        }
    }
}
